site:
  title: Decidim Docs
  url: https://docs.decidim.org
  start_page: master@en:ROOT:index.adoc
content:
  edit_url: 'https://github.com/decidim/documentation/edit/{refname}/{path}'
  sources:
  - url: &landing .
    start_path: /en
    branches: HEAD
  - url: https://github.com/decidim/decidim
    start_path: docs
    branches: main
ui:
  bundle:
    url: https://github.com/decidim/documentation-antora-ui/releases/download/v0.3/ui-bundle.zip
    snapshot: true
  supplemental_files: ./supplemental_ui
asciidoc:
  attributes:
    kroki-fetch-diagram: true
    page-pagination: ''
  extensions:
    - asciidoctor-kroki
