site:
  title: Decidim Docs (JA)
  url: https://decidim-docs-ja.netlify.app
  start_page: master@ja:ROOT:index.adoc
content:
  edit_url: 'https://github.com/takahashim/decidim-documentation/edit/{refname}/{path}'
  sources:
  - url: &landing .
    start_path: /ja
    branches: HEAD
  - url: https://github.com/decidim/decidim
    start_path: docs
    branches: develop
ui:
  bundle:
    url: https://github.com/decidim/documentation-antora-ui/releases/download/v0.3/ui-bundle.zip
    snapshot: true
  supplemental_files: ./supplemental_ui
asciidoc:
  attributes:
    kroki-fetch-diagram: true
    page-pagination: ''
  extensions:
    - asciidoctor-kroki
